### ISSUE TITLE
Retrieve certificate with its private key

### ISSUE THREAD

**Issue by VelinGeorgiev** [ukoloff/win-ca#13]
Is there a way retrieve the cert with its private key to be used for creating/signing jwt token?

**Comment by VelinGeorgiev** [comment]
Please ignore. Seems the key cannot be exported.

![image](https://user-images.githubusercontent.com/1049476/52414338-edf56e80-2adb-11e9-967f-8172927a11fa.png)


I will have to find out how Microsoft libraries are working to create client assertion using certificate from the Windows store using . They need to have a way to export the private key to sign the token
```
X509Store certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);

X509Certificate2Collection x509Certificate2Collection = x509Store.Certificates.Find(X509FindType.FindByThumbprint, thumbprint, validOnly: false);


certCred = new ClientAssertionCertificate(clientId, cert);

result = await authContext.AcquireTokenAsync(todoListResourceId, certCred);
```

**Comment by ukoloff** [comment]
Some notes on the subject:

1. `win-ca` works with certificates only, no keys at all

2. In order to export private key from Windows store, it should have been created (or imported) with `Exportable` flag.

3. I believe there should exist Win32 API call to sign something with private key (from Windows store) without exporting it first (even with non-exportable key). But even if it exists, calling it from Node.js would be tricky. I'd recommend not to mess with it

4. Even on Windows, I would use portable format for private keys (as generated by `OpenSSL` for example), since Node.js uses it everywhere.


[pkcs12]: https://en.wikipedia.org/wiki/PKCS_12

**Comment by VelinGeorgiev** [comment]
Thank you Stas! 

I came to pretty much the same conclusion. My case is very specific since for extra security it is required to store the cert in Azure app service cert storage that is basically windows cert storage on a virtual machine in Azure. 

I have now a backup plan to use c sharp service to get the cert and issue a token (working in vnet with no exposure to internet) and then all the node apps will just use it. This will be a working solution that comply with the requirements.

Thanks again!
