### ISSUE TITLE
Ignoring "save" parameter path

### ISSUE THREAD

**Issue by adammeyer** [ukoloff/win-ca#17]
I'm using win-ca in an elecron app, but in a forked process, so "is-electron" returns false.

This is my implementation:
```
require('win-ca')({save: (process.env.USERPROFILE || process.env.HOME) + '\\.local\\win-ca\\pem'});
```

Everything works wonderfully in development, but when I build a release, it fails.

C:\Users\adam\\.local\win-ca\pem\roots.pem is created, but it's 0 bytes and the forked process crashes with this error:
```
Error: EPERM: operation not permitted, open 'C:\\Program Files\\app\resources\\app.asar.unpacked\\node_modules\\win-ca\\pem\\roots.pem'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

Why is it attempting to use the asar path when I have set the "save" path to a different path?  Does it need to be set somewhere else as well?

Thank you!

**Comment by ukoloff** [comment]
I will look at this issue in details later, but here are my first considerations:

1) If Electron is not detectable you should better `require("win-ca/fallback")` or `ca({fallback: true, ...})`

2) When you do `require('win-ca')` certificates are fetched and stored to standard location (`.../node_modules/win-ca/pem`). To skip this step you should `require('win-ca/api')`

3) How is forked process supposed to know where it should look for PEM file? Does it use `SSL_CERT_DIR` env. var? It is set by automatic saving during `require('win-ca')` and is NOT set by `ca({save: ...})`. Undocumented feature exists: `ca({$ave: ...})`, it works like `save` (note difference in name), but also sets `SSL_CERT_DIR`. But I'd recommend to use `onsave` callback and pass parameters explicitly in your code.

4) What is the difference between `release` and `development` modes in your setup? It is just env. variable or something else changes?

5) When `roots.pem` is of zero length, are there other files in that folder (like `abc5123f.0`)?

6) Instead of `process.env.USERPROFILE || process.env.HOME` I'm planning to switch to `os.homedir()`. It has nothing with this issue, just more elegant.

Finally, my idea is to try:
```js
require('win-ca/api')({
  fallback: true,
  save: path.join(os.homedir(), '.local/win-ca/pem'),
  onsave: path => console.log('PATH', path)
})
```

**Comment by adammeyer** [comment]
Thank you!  Your solution worked great.

The difference between dev and release is that release combines all JS files into one asar file.  It's also installed in the Program Files directory, so it's not writable.

I now get the certs in the main process, then pass in the roots.pem path to the forked process for use.  I'm not using any env vars.

**Comment by ukoloff** [comment]
Good news! :-)
