### ISSUE TITLE
"Error: Self signed certificate in certificate chain" in win 10 

### ISSUE THREAD

**Issue by monema75** [ukoloff/win-ca#6]
I am receiving a "self signed certificate in certificate chain" in a fresh windows 10 installation with default certificates. Working correctly in win 8.1.
self signed certificate in certificate chain at TLSSocket.<anonymous> (_tls_wrap.js:1103:38) at emitNone (events.js:105:13) at TLSSocket.emit (events.js:207:7) at TLSSocket._finishInit (_tls_wrap.js:637:8) at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)

Any clues?

**Comment by ukoloff** [comment]
1) What server are you connecting to? Is it world-readable or intranet?
2) Can you get its CA certificate and attach here?

**Comment by monema75** [comment]
My app does not know beforehand if the server will have certificate or not. I call win-ca during the launch of the app. In win 8.1 the behaviour is correct both if server does or does not have certificate.
When using win 10 though I have the error in both cases

**Comment by ukoloff** [comment]
1) Do Windows 8 version and Windows 10 version generate the same root.pem file?

2) I see NO self-made certificates in `root.pem` you sent. If you don't use your own root CA, `win-ca` is of no use.

3) What do you mean: server will have certificate or not? Connection is sometimes secure, sometimes unsecure?

4) Do you use `https` Node module or just `tls`? The former is automagicaly patched by `win-ca`, the latter is not (and should be patched explicitly).

**Comment by ukoloff** [comment]
To tell the truth I never tested `win-ca` on Win 10. I have no one to test on.

But you can do it yourself. Write minimal Node.js program to connect to some well known https site. In Russia we use https://ya.ru

E.g.
```js
require('win-ca')
https = require('https')

var uri

https.get(uri = 'https://ya.ru', =>
  console.log("HTTPS GET", uri, "succeeded.")
```

Run it. Then comment out `require('win-ca')` and run again. What happens?

**Comment by monema75** [comment]
Using same ya.ru site.
**WITH win-ca:**
```
{ Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
```

**WITHOUT win-ca**
`HTTPS GET https://ya.ru succeeded.`

**Comment by monema75** [comment]
As far as I have checked the problem is not consistent in all win 10 versions.
Up until now:
* Windows 10 Enterprise v. 1607 --> √ Works correctly
* Windows 10 Enterprise v. 1709 --> X Error
* Windows 10 Enterprise v. 1803 --> X Error

**Comment by ukoloff** [comment]
Oops! Microsoft is likely to change Win32 crypto API... I'll try to fix this, but not immediately, I'm a bit busy right now.

**Comment by xaviergonz** [comment]
Just wondering, was this ever fixed?

**Comment by ukoloff** [comment]
@xaviergonz Alas, not yet. I have no modern Windows installed, still using 7. 

Well, since there are someone still interested, I'll try to install 10 in Virtual Box.

**Comment by ukoloff** [comment]
It seems, fresh installed Windows 10 have a lot of Root CA [missed][]:

- 02265526.0 Entrust Root Certification Authority - G2
- 062cdee6.0 GlobalSign
- 244b5494.0 DigiCert High Assurance EV Root CA
- 2c3e3f84.0 UTN-USERFirst-Object
- 2c543cd1.0 GeoTrust Global CA
- 2e4eed3c.0 thawte Primary Root CA
- 48bec511.0 Certum Trusted Network CA
- 4bfab552.0 Starfield Root Certificate Authority - G2
- 578d5c04.0 Equifax Secure Certificate Authority
- 6b99d060.0 Entrust Root Certification Authority
- 98ec67f0.0 premium-server@thawte.com
- ae8153b9.0 StartCom Certification Authority
- c692a373.0 GTE CyberTrust Global Root
- cbf06781.0 Go Daddy Root Certificate Authority - G2
- f39fc864.0 SecureTrust CA

If you open Edge and go to https://ya.ru - `Certum` is loaded (since Yandex is signed by it) and added to Root CA list behind the scene! If you go to https://github.com/ - `DigiCert` is installed etc.

I'm afraid, `win-ca` can do nothing with this. Just open M$ Edge and navigate __once__ to the site you need to connect with the script.

I hope, Group Policy should apply without manual intervention (just wait a little)...

There must exist a way to force update Windows Trusted Root list, but I cannot find it. Simple `gpupdate` doesn't work for me. `rootsupd.exe` utility for doing this has been removed from M$ website.

[missed]: https://social.technet.microsoft.com/Forums/office/en-US/65224f3a-37e3-4e61-9f42-d2e80949d7a2/updating-trusted-root-certificates-for-new-win-10-gold-image?forum=win10itprosecurity

**Comment by xaviergonz** [comment]
Could there be an option then so win-CA mixes node built in certificates with windows ones? (assuming that's not done already)

**Comment by ukoloff** [comment]
As far as I know, Node.js' built-in certificates are not accesible to scripts. Either use just them or use your own list.

**Comment by ukoloff** [comment]
Wow, [starting with Windows Vista, root CA certificates are typically installed on demand][demand]. 

But this functionality is clearly unavailable for Node.js programs :-(

So, if you connect to well-known sites (like Google, GitHub, Yandex etc.) you'd rather NOT use `win-ca`.

If you connect to intranet and your Root CA is distributed via Group Policy - `win-ca` should work for you.

If you connect to both - you are in trouble. Thank you, Microsoft! ;-)

[demand]: https://social.technet.microsoft.com/wiki/contents/articles/3147.pki-certificate-chaining-engine-cce.aspx

**Comment by chrmarti** [comment]
FYI: @capriza found a way to add CAs on top of the built-in ones: https://github.com/capriza/syswide-cas/blob/e0a214f23a072866abf6af540a5b4b88b892a109/index.js#L93

**Comment by ukoloff** [comment]
Oh, he patches `tls.createSecureContext` instead. This may be a good idea, but it requires some exploration.

**Comment by ukoloff** [comment]
If you're still interested: win-ca@3 is [published][npm].

It supports new method by capriza. Minimal code is:
```js
require('win-ca').inject('+')
```
VS Code extension is [updated][ext] too. It has configuration parameters now, setting `inject` to `append` is supposed to do the trick.

[npm]: https://www.npmjs.com/package/win-ca
[ext]: https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca
